# Generated by Django 3.1 on 2020-08-24 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("trigger_song_spotify_id", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("last_activated", models.DateTimeField(blank=True, default=None)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongSequenceMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_spotify_id", models.CharField(max_length=64)),
                ("sequence_number", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_sequence",
                        to="data.rule",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="songsequencemember",
            constraint=models.UniqueConstraint(
                fields=("rule", "sequence_number"), name="unique_rule_sequence_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="rule",
            constraint=models.UniqueConstraint(
                fields=("trigger_song_spotify_id", "owner"), name="unique_song_owner"
            ),
        ),
        migrations.CreateModel(
            name="UserLock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="rule",
            old_name="last_activated",
            new_name="last_applied",
        ),
        migrations.AlterField(
            model_name="rule",
            name="last_applied",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="LastCheckLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_checked", models.DateTimeField(db_index=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_check_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="songsequencemember",
            options={"ordering": ["sequence_number"]},
        ),
        migrations.AddField(
            model_name="rule",
            name="name",
            field=models.CharField(default="Unnamed", max_length=256),
        ),
        migrations.AddField(
            model_name="songsequencemember",
            name="name",
            field=models.CharField(default="Unnamed", max_length=256),
        ),
    ]
