name: Queue Rules Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install
      run: make dev-build
    - name: Test
      run: make test
    - name: Lint
      run: make lint
    - name: Build web image
      run: docker build . --file web.Dockerfile
    - name: Build queuerd image
      run: docker build . --file queuerd.Dockerfile
